### ISSUE TITLE
急！手动组网添加默认账户时一直拒绝连接 8250

### ISSUE THREAD

**Issue by jiuhao666** [WeBankBlockchain/WeCross#582]
在手动组网环节
1重启跨链路由加载已配置的跨链资源以后，按照文档 使用“tail -f logs/info.log |grep "active resources”命令无法加载出活跃的跨链资源。
2.配置跨链账户中，启动控制台后使用默认的跨链账户登录：org1-admin，密码：123456（默认账户在WeCross-Account-Manager/conf/application.toml配置），显示拒绝连接127.0.0.1:8250

![image](https://github.com/WeBankBlockchain/WeCross/assets/102295407/3b76d063-ff9f-454b-afc3-c1e2bac69e6d)

从网上找了很多关于这方面的解决办法仍无法解决，特此求助各位大佬

**Comment by kyonRay** [comment]
是不是有多机部署？看看router是不是监听的是127.0.0.1

**Comment by kyonRay** [comment]
说明你的router没有部署在本地。是在其他机器中部署的。

要远程访问router必须要将router的RPC监听到0.0.0.0，例如：

```toml
[rpc] # rpc ip & port
    address = '0.0.0.0' # router监听IP
    port = 8250
    caCert = 'classpath:ca.crt'
    sslCert = 'classpath:ssl.crt'
    sslKey = 'classpath:ssl.key'
    sslSwitch = 2  # disable ssl:2, SSL without client auth:1 , SSL with client and server auth: 0
    webRoot = 'classpath:pages'
    mimeTypesFile = 'classpath:conf/mime.types' # set the content-types of a file
```
